apiVersion: apps/v1
kind: Deployment
metadata:
  name: play-identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: play-identity
  template:
    metadata:
      labels:
        app: play-identity
    spec:
      containers:
        - name: play-identity
          image: playeconomyapp.azurecr.io/play-identity:IMAGE_TAG_PLACEHOLDER
          ports:
            - containerPort: 80
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_URI
